name: Deploy to EC2

on:
  push:
    branches: [ "main" ]  # or whichever branches you want to auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Remove .git folder
        run: rm -rf .git

      - name: Copy front-end files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "roomie-webapp/*"
          target: "/var/www/html/"
          overwrite: true

      - name: Create directory with sudo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /opt/roomiebackend
            sudo chown $USER:$USER /opt/roomiebackend

      - name: Copy back-end files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "roomiebackend/*"
          target: "/opt/roomiebackend"            
          overwrite: true

      - name: Run remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/Roomie
            # e.g. install dependencies or run build steps
            # For example:
            # npm install
            # npm run build
            sudo systemctl daemon-reload
